name: pis_house_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

assets:
  - assets/fonts/

fonts:
  - family: Lato
    fonts:
      - asset: assets/fonts/Lato/Lato-Thin.ttf
        weight: 100
      - asset: assets/fonts/Lato/Lato-Light.ttf
        weight: 300
      - asset: assets/fonts/Lato/Lato-Regular.ttf
        weight: 400
      - asset: assets/fonts/Lato/Lato-Bold.ttf
        weight: 700
      - asset: assets/fonts/Lato/Lato-Black.ttf
        weight: 900


environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.6.1
  built_collection: ^5.1.1
  cupertino_icons: ^1.0.8
  go_router: ^16.2.1
  flutter_hooks: ^0.21.3+1
  json_annotation: ^4.9.0
  firebase_database: ^12.0.1
  firebase_core: ^4.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0

flutter:

  uses-material-design: true